name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Install dependencies for frontend
      - name: Install dependencies for frontend
        run: |
          cd chatbot-app
          npm install
          chmod +x node_modules/.bin/react-scripts


      # Install dependencies for backend (Azure Function API - Node.js)
      - name: Install dependencies for Azure Function API
        run: |
          cd api
          npm install

      # (Optional) Build API if needed
      - name: Build Azure Function API (if needed)
        run: |
          cd api
          npm run build || echo "No build step defined, skipping..."

      # Build frontend
      - name: Build frontend
        run: |
          cd chatbot-app
          npm run build

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_BAY_06B08411E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "src"
          api_location: "api"  # Correct path to your API
          output_location: "build"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_BAY_06B08411E }}
          action: "close"


