name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Install dependencies for frontend
      - name: Install dependencies for frontend
        run: |
          cd chatbot-app
          npm install --force
          chmod +x node_modules/.bin/react-scripts

      # Install dependencies for backend (Azure Function API)
      - name: Install dependencies for Azure Function API
        run: |
          cd api
          npm install

      # Build frontend
      - name: Build frontend
        run: |
          cd chatbot-app
          npm run build

      # Build Azure Function API (om .NET används)
      - name: Build Azure Function API (.NET)
        run: |
          cd api
          dotnet build --configuration Release

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_BAY_06B08411E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./chatbot-app"
          api_location: "./ChatBot/api" # RÄTT API-PATH
          output_location: "build"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_BAY_06B08411E }}
          action: "close"


